// app/layout.tsx
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { euclidCircular } from './fonts';
import "./globals.css";

const roboto = Roboto({
    weight: ["100", "300", "400", "500", "700", "900"],
    variable: "--font-roboto",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Точки питания по Москве",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${euclidCircular.variable}`}>
        <head>
            <link rel="icon" type="image/svg+xml" href="/logo.jpg"/>
        </head>
            <body className="font-euclid antialiased">
                {children}
            </body>
        </html>
    );
}